 metadata:
   name: emp-deployment-management
 spec:
   replicas: 2
   template:
     metadata:
       name: emp-management
       labels:
         app: emp-management
     spec:
       containers:
         - name: emp-management
           image: shubh1sinha/employee-management-react:1.0
           imagePullPolicy: Always
   selector:
     matchLabels:
      app: emp-management