apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-deployment-management
   
spec:
  replicas: 1
  template:
    metadata:
      name: emp-management
      labels:
        app: emp-app
    spec:
      containers:
        - name: emp-container
          image: shubh1sinha/employee-management-react:1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '1'
              memory: '500Mi'
            requests:
              cpu: '1'
              memory: '500Mi'
  selector:
    matchLabels:
     app: emp-app