 apiVersion: apps/v1
 kind: Deployment
 metadata:
   labels:
     app: emp-app
   name: emp-deployment-management
 spec:
   replicas: 2
   template:
     metadata:
       name: emp-management
       labels:
         app: emp-app
     spec:
       containers:
         - name: emp-container
           image: shubh1sinha/employee-management-react:1.0
           imagePullPolicy: Always
   selector:
     matchLabels:
      app: emp-app