apiVersion: v1
kind: Service
metadata:
  name: emp-service-management
  labels:
    app: emp-app
spec:
  selector:
    app: emp-app
  type: LoadBalancer
  ports:
  - nodePort: 32751
    port: 80
    targetPort: 3000
