apiVersion: v1
kind: Service
metadata:
  name: emp-service-management
  labels:
    app: emp-management
spec:
  selector:
    app: emp-management
  type: LoadBalancer
  ports:
  - nodePort: 32752
    port: 80
    targetPort: 3001
